
import { AcupuncturePoint } from './types';

export const MERIDIANS = [
  { code: 'LU', name: 'Pulmón', color: 'bg-slate-400' },
  { code: 'LI', name: 'Intestino Grueso', color: 'bg-yellow-600' },
  { code: 'ST', name: 'Estómago', color: 'bg-yellow-400' },
  { code: 'SP', name: 'Bazo', color: 'bg-yellow-500' },
  { code: 'HT', name: 'Corazón', color: 'bg-red-500' },
  { code: 'SI', name: 'Intestino Delgado', color: 'bg-red-600' },
  { code: 'BL', name: 'Vejiga', color: 'bg-blue-600' },
  { code: 'KI', name: 'Riñón', color: 'bg-blue-800' },
  { code: 'PC', name: 'Pericardio', color: 'bg-red-400' },
  { code: 'SJ', name: 'San Jiao', color: 'bg-orange-500' },
  { code: 'GB', name: 'Vesícula Biliar', color: 'bg-green-600' },
  { code: 'LR', name: 'Hígado', color: 'bg-green-800' },
  { code: 'GV', name: 'Du Mai (Gobernador)', color: 'bg-purple-600' },
  { code: 'CV', name: 'Ren Mai (Concepción)', color: 'bg-indigo-600' },
];

// Imagen única proporcionada para el meridiano de Pulmón
const IMG_LUNG_MAP = "https://i.ibb.co/XfqM9Gkz/lung-channel-map.jpg"; 

export const INITIAL_POINTS: AcupuncturePoint[] = [
  {
    id: 'LU1',
    name: 'Zhongfu',
    pinyin: 'Zhōngfǔ',
    meridian: 'LU',
    meridianName: 'Pulmón',
    location: 'En la parte lateral del pecho, en el 1er espacio intercostal, 6 cun lateral a la línea media anterior.',
    indications: ['Tos', 'Asma', 'Opresión torácica', 'Dolor de hombro y espalda'],
    contraindications: ['Punción profunda prohibida (riesgo de neumotórax).'],
    applications: 'Tratamiento de exceso de moco, bronquitis aguda y asma.',
    benefits: 'Punto Mu Frontal del Pulmón. Regula el Qi de pulmón, transforma la flema y despeja el calor.',
    techniques: 'Inserción oblicua 0.5-0.8 cun hacia la parte lateral del tórax.',
    observations: 'Punto de intersección con el meridiano de Bazo.',
    staticImage: IMG_LUNG_MAP
  },
  {
    id: 'LU2',
    name: 'Yunmen',
    pinyin: 'Yúnmén',
    meridian: 'LU',
    meridianName: 'Pulmón',
    location: 'En la fosa infraclavicular, en la depresión medial al proceso coracoides.',
    indications: ['Tos', 'Asma', 'Dolor en el pecho y hombro'],
    contraindications: ['No punción profunda (neumotórax).'],
    applications: 'Alivio de la opresión en el tórax superior y agitación.',
    benefits: 'Despeja el pulmón y detiene la tos. Abre el tórax.',
    techniques: 'Inserción oblicua 0.5-0.8 cun.',
    observations: 'Significa "Puerta de las Nubes".',
    staticImage: IMG_LUNG_MAP
  },
  {
    id: 'LU3',
    name: 'Tianfu',
    pinyin: 'Tiānfǔ',
    meridian: 'LU',
    meridianName: 'Pulmón',
    location: 'En la cara radial del brazo, 3 cun por debajo del extremo del pliegue axilar.',
    indications: ['Hemorragia nasal', 'Asma', 'Tos', 'Dolor en el brazo'],
    contraindications: ['Ninguna.'],
    applications: 'Trastornos emocionales relacionados con el pulmón (tristeza).',
    benefits: 'Punto "Ventana del Cielo". Calma el espíritu y regula el Qi.',
    techniques: 'Inserción perpendicular 0.5-1.0 cun.',
    observations: 'Punto importante para la conexión pulmón-mente.',
    staticImage: IMG_LUNG_MAP
  },
  {
    id: 'LU4',
    name: 'Xiabai',
    pinyin: 'Xiábái',
    meridian: 'LU',
    meridianName: 'Pulmón',
    location: 'En la cara radial del brazo, 4 cun por debajo del extremo del pliegue axilar.',
    indications: ['Tos', 'Dolor en el pecho', 'Palpitaciones', 'Dolor de brazo'],
    contraindications: ['Ninguna.'],
    applications: 'Tos con dolor irradiado al brazo.',
    benefits: 'Regula el Qi y la sangre, calma el dolor.',
    techniques: 'Inserción perpendicular 0.5-1.0 cun.',
    observations: 'Significa "Blanco Protector".',
    staticImage: IMG_LUNG_MAP
  },
  {
    id: 'LU5',
    name: 'Chize',
    pinyin: 'Chǐzé',
    meridian: 'LU',
    meridianName: 'Pulmón',
    location: 'En el pliegue del codo, en el borde radial del tendón del bíceps braquial.',
    indications: ['Fiebre', 'Tos con flema', 'Asma', 'Dolor de garganta', 'Vómitos'],
    contraindications: ['Evitar arteria braquial.'],
    applications: 'Bronquitis, amigdalitis, dolores de codo y brazo.',
    benefits: 'Punto He-Mar (Agua). Despeja el calor de pulmón y desciende el Qi rebelde.',
    techniques: 'Inserción perpendicular 0.5-1.0 cun.',
    observations: 'Punto de sedación del meridiano.',
    staticImage: IMG_LUNG_MAP
  },
  {
    id: 'LU6',
    name: 'Kongzui',
    pinyin: 'Kǒngzuì',
    meridian: 'LU',
    meridianName: 'Pulmón',
    location: 'Cara radial del antebrazo, 7 cun por encima del pliegue de la muñeca.',
    indications: ['Hemoptisis', 'Dolor de garganta', 'Asma aguda', 'Cough'],
    contraindications: ['Ninguna.'],
    applications: 'Crisis asmáticas, hemorragias pulmonares súbitas.',
    benefits: 'Punto Xi-Hendidura. Detiene hemorragias y alivia casos agudos.',
    techniques: 'Inserción perpendicular 0.5-1.2 cun.',
    observations: 'Excelente para el tratamiento de síntomas pulmonares severos repentinos.',
    staticImage: IMG_LUNG_MAP
  },
  {
    id: 'LU7',
    name: 'Lieque',
    pinyin: 'Lièquē',
    meridian: 'LU',
    meridianName: 'Pulmón',
    location: '1.5 cun sobre el pliegue de la muñeca, en la depresión del proceso estiloides del radio.',
    indications: ['Cefalea', 'Rigidez de nuca', 'Tos', 'Parálisis facial'],
    contraindications: ['Ninguna.'],
    applications: 'Gripe, resfriado, migrañas temporales.',
    benefits: 'Punto Luo. Maestro del Ren Mai. Comando de la nuca y cabeza.',
    techniques: 'Inserción oblicua 0.3-0.5 cun hacia el codo.',
    observations: 'Punto fundamental para expulsar el viento externo.',
    staticImage: IMG_LUNG_MAP
  },
  {
    id: 'LU8',
    name: 'Jingqu',
    pinyin: 'Jīngqú',
    meridian: 'LU',
    meridianName: 'Pulmón',
    location: '1 cun sobre el pliegue de la muñeca, en la depresión medial al estiloides radial.',
    indications: ['Asma', 'Tos', 'Dolor de garganta', 'Fiebre'],
    contraindications: ['No se recomienda moxibustión directa.'],
    applications: 'Tratamiento de la tos crónica y asma.',
    benefits: 'Punto Jing-Río (Metal). Punto de tonificación.',
    techniques: 'Inserción perpendicular 0.3-0.5 cun.',
    observations: 'Significa "Canal del Paso".',
    staticImage: IMG_LUNG_MAP
  },
  {
    id: 'LU9',
    name: 'Taiyuan',
    pinyin: 'Tàiyuán',
    meridian: 'LU',
    meridianName: 'Pulmón',
    location: 'En el pliegue de la muñeca, en la fosa lateral a la arteria radial.',
    indications: ['Asma', 'Tos', 'Debilidad de pulso', 'Dolor de pecho'],
    contraindications: ['Evitar arteria radial.'],
    applications: 'Tonificación general del Qi y Yin de pulmón.',
    benefits: 'Punto Shu-Arroyo. Punto Yuan. Punto Influente de los Vasos.',
    techniques: 'Inserción perpendicular 0.3-0.5 cun.',
    observations: 'Punto muy importante para nutrir el órgano pulmón.',
    staticImage: IMG_LUNG_MAP
  },
  {
    id: 'LU10',
    name: 'Yuji',
    pinyin: 'Yújì',
    meridian: 'LU',
    meridianName: 'Pulmón',
    location: 'En el punto medio del primer hueso metacarpiano, borde piel roja y blanca.',
    indications: ['Fiebre', 'Dolor de garganta', 'Hemoptisis', 'Tos'],
    contraindications: ['Ninguna.'],
    applications: 'Amigdalitis aguda y calor en las palmas.',
    benefits: 'Punto Ying-Manantial (Fuego). Despeja calor de pulmón y beneficia la garganta.',
    techniques: 'Inserción perpendicular 0.5-0.8 cun.',
    observations: 'Punto clave para el "Calor de Pulmón".',
    staticImage: IMG_LUNG_MAP
  },
  {
    id: 'LU11',
    name: 'Shaoshang',
    pinyin: 'Shàoshāng',
    meridian: 'LU',
    meridianName: 'Pulmón',
    location: 'En el lado radial del pulgar, 0.1 cun proximal a la esquina de la uña.',
    indications: ['Pérdida de conciencia', 'Dolor de garganta agudo', 'Manía', 'Fiebre alta'],
    contraindications: ['Ninguna.'],
    applications: 'Casos de emergencia y reanimación.',
    benefits: 'Punto Jing-Pozo (Madera). Despeja el calor y abre los orificios.',
    techniques: 'Inserción superficial 0.1 cun o sangría.',
    observations: 'Se suele pinchar para sangrar en amigdalitis severas.',
    staticImage: IMG_LUNG_MAP
  },
  {
    id: 'LI1',
    name: 'Shangyang',
    pinyin: 'Shangyang',
    meridian: 'LI',
    meridianName: 'Intestino Grueso',
    location: '0.1 cun proximal al ángulo ungueal radial del dedo índice',
    indications: ['Faringitis aguda', 'fiebre', 'dolor dental'],
    contraindications: ['Punción superficial o sangría leve'],
    applications: 'Punto Jing-Well; estimulación refleja del SNC; posible efecto antipirético',
    benefits: 'Dermatoma C6; terminaciones nerviosas digitales',
    techniques: '0.1 cun superficial',
    observations: 'Ilustrar LI-1 en el ángulo ungueal radial del dedo índice'
  },
  {
    id: 'LI2',
    name: 'Erjian',
    pinyin: 'Erjian',
    meridian: 'LI',
    meridianName: 'Intestino Grueso',
    location: 'Depresión distal a la articulación metacarpofalángica del índice, lado radial',
    indications: ['Gingivitis', 'odontalgia', 'inflamación local'],
    contraindications: ['Sin riesgo mayor'],
    applications: 'Punto Ying; posible modulación inflamatoria',
    benefits: 'Nervios digitales dorsales',
    techniques: '0.2–0.3 cun',
    observations: 'Ilustrar LI-2 distal a la articulación MCP del índice'
  },
  {
    id: 'LI3',
    name: 'Sanjian',
    pinyin: 'Sanjian',
    meridian: 'LI',
    meridianName: 'Intestino Grueso',
    location: 'Proximal a la cabeza del segundo metacarpiano, lado radial',
    indications: ['Dolor mano', 'inflamación dorsal'],
    contraindications: ['Sin riesgo mayor'],
    applications: 'Punto Shu; efecto analgésico segmentario',
    benefits: 'Nervio radial superficial',
    techniques: '0.5–0.8 cun',
    observations: 'Ilustrar LI-3 proximal al segundo metacarpiano'
  },
  {
    id: 'LI4',
    name: 'Hegu',
    pinyin: 'Hegu',
    meridian: 'LI',
    meridianName: 'Intestino Grueso',
    location: 'Dorso de la mano, entre 1° y 2° metacarpiano, punto medio del 2° metacarpiano',
    indications: ['Cefalea', 'migraña', 'dolor facial', 'sinusitis', 'dolor general'],
    contraindications: ['Contraindicado en embarazo'],
    applications: 'Punto Yuan; modulación descendente del dolor; liberación de endorfinas',
    benefits: 'Dermatoma C6; nervio radial',
    techniques: '0.5–1 cun',
    observations: 'Ilustrar LI-4 entre primer y segundo metacarpiano'
  },
  {
    id: 'LI5',
    name: 'Yangxi',
    pinyin: 'Yangxi',
    meridian: 'LI',
    meridianName: 'Intestino Grueso',
    location: 'Depresión en tabaquera anatómica radial',
    indications: ['Tendinitis muñeca', 'dolor radial'],
    contraindications: ['Evitar arteria radial'],
    applications: 'Punto Jing-River; efecto antiinflamatorio local',
    benefits: 'Arteria radial subyacente',
    techniques: '0.3–0.5 cun',
    observations: 'Ilustrar LI-5 en tabaquera anatómica'
  },
  {
    id: 'LI6',
    name: 'Pianli',
    pinyin: 'Pianli',
    meridian: 'LI',
    meridianName: 'Intestino Grueso',
    location: '3 cun proximal a LI-5 en línea hacia LI-11',
    indications: ['Edema facial', 'tinnitus'],
    contraindications: ['Sin riesgo mayor'],
    applications: 'Punto Luo; posible modulación autonómica',
    benefits: 'Nervio radial superficial',
    techniques: '0.5–0.8 cun',
    observations: 'Ilustrar LI-6 a 3 cun sobre LI-5'
  },
  {
    id: 'LI7',
    name: 'Wenliu',
    pinyin: 'Wenliu',
    meridian: 'LI',
    meridianName: 'Intestino Grueso',
    location: '5 cun proximal a LI-5',
    indications: ['Dolor agudo brazo', 'inflamación'],
    contraindications: ['Precaución vascular'],
    applications: 'Punto Xi; analgesia segmentaria rápida',
    benefits: 'Territorio radial',
    techniques: '0.5–1 cun',
    observations: 'Ilustrar LI-7 a 5 cun sobre muñeca'
  },
  {
    id: 'LI8',
    name: 'Xialian',
    pinyin: 'Xialian',
    meridian: 'LI',
    meridianName: 'Intestino Grueso',
    location: '4 cun distal a LI-11 en línea radial antebrazo',
    indications: ['Dolor antebrazo', 'dispepsia funcional'],
    contraindications: ['Sin riesgo mayor'],
    applications: 'Regulación refleja visceral',
    benefits: 'Dermatoma C7',
    techniques: '0.5–1 cun',
    observations: 'Ilustrar LI-8 en antebrazo radial'
  },
  {
    id: 'LI9',
    name: 'Shanglian',
    pinyin: 'Shanglian',
    meridian: 'LI',
    meridianName: 'Intestino Grueso',
    location: '3 cun distal a LI-11',
    indications: ['Parestesias miembro superior'],
    contraindications: ['Sin riesgo mayor'],
    applications: 'Acción segmentaria brazo',
    benefits: 'Nervio radial',
    techniques: '0.5–1 cun',
    observations: 'Ilustrar LI-9 en línea radial antebrazo'
  },
  {
    id: 'LI10',
    name: 'Shousanli',
    pinyin: 'Shousanli',
    meridian: 'LI',
    meridianName: 'Intestino Grueso',
    location: '2 cun distal a LI-11',
    indications: ['Debilidad muscular brazo'],
    contraindications: ['Sin riesgo mayor'],
    applications: 'Activación neuromuscular',
    benefits: 'Miotoma C6–C7',
    techniques: '0.8–1.2 cun',
    observations: 'Ilustrar LI-10 2 cun bajo LI-11'
  },
  {
    id: 'LI11',
    name: 'Quchi',
    pinyin: 'Quchi',
    meridian: 'LI',
    meridianName: 'Intestino Grueso',
    location: 'Extremo lateral del pliegue cubital con codo flexionado',
    indications: ['Inflamación sistémica', 'dermatitis', 'hipertensión leve'],
    contraindications: ['Precaución vascular profunda'],
    applications: 'Punto He-Sea; modulación inmunitaria e inflamatoria',
    benefits: 'Nervio radial profundo',
    techniques: '1–1.5 cun',
    observations: 'Ilustrar LI-11 en extremo lateral pliegue cubital'
  },
  {
    id: 'LI12',
    name: 'Zhouliao',
    pinyin: 'Zhouliao',
    meridian: 'LI',
    meridianName: 'Intestino Grueso',
    location: '1 cun proximal a LI-11',
    indications: ['Dolor codo'],
    contraindications: ['Sin riesgo mayor'],
    applications: 'Acción local miofascial',
    benefits: 'Tejido muscular braquial',
    techniques: '0.5–1 cun',
    observations: 'Ilustrar LI-12 sobre LI-11'
  },
  {
    id: 'LI13',
    name: 'Shouwuli',
    pinyin: 'Shouwuli',
    meridian: 'LI',
    meridianName: 'Intestino Grueso',
    location: '3 cun proximal a LI-11',
    indications: ['Contractura brazo'],
    contraindications: ['Sin riesgo mayor'],
    applications: 'Liberación miofascial',
    benefits: 'Territorio radial',
    techniques: '0.5–1 cun',
    observations: 'Ilustrar LI-13 3 cun sobre LI-11'
  },
  {
    id: 'LI14',
    name: 'Binao',
    pinyin: 'Binao',
    meridian: 'LI',
    meridianName: 'Intestino Grueso',
    location: '7 cun proximal a LI-11 en deltoides',
    indications: ['Dolor hombro'],
    contraindications: ['Sin riesgo mayor'],
    applications: 'Acción sobre deltoides',
    benefits: 'Nervio axilar cercano',
    techniques: '0.8–1.5 cun',
    observations: 'Ilustrar LI-14 en región deltoidea'
  },
  {
    id: 'LI15',
    name: 'Jianyu',
    pinyin: 'Jianyu',
    meridian: 'LI',
    meridianName: 'Intestino Grueso',
    location: 'Depresión anterior e inferior al acromion',
    indications: ['Hombro doloroso', 'capsulitis'],
    contraindications: ['Precaución estructuras subacromiales'],
    applications: 'Mejora movilidad articular',
    benefits: 'Nervio axilar',
    techniques: '1–1.5 cun',
    observations: 'Ilustrar LI-15 bajo acromion'
  },
  {
    id: 'LI16',
    name: 'Jugu',
    pinyin: 'Jugu',
    meridian: 'LI',
    meridianName: 'Intestino Grueso',
    location: 'Depresión entre clavícula y acromion',
    indications: ['Dolor hombro superior'],
    contraindications: ['Precaución pleural profunda'],
    applications: 'Acción miofascial clavicular',
    benefits: 'Cercanía pleura superior',
    techniques: '0.5–1 cun',
    observations: 'Ilustrar LI-16 entre clavícula y acromion'
  },
  {
    id: 'LI17',
    name: 'Tianding',
    pinyin: 'Tianding',
    meridian: 'LI',
    meridianName: 'Intestino Grueso',
    location: 'Nivel cartílago tiroides, borde posterior ECM',
    indications: ['Dolor garganta'],
    contraindications: ['Evitar arteria carótida'],
    applications: 'Modulación cervical anterior',
    benefits: 'Arteria carótida cercana',
    techniques: '0.5–1 cun',
    observations: 'Ilustrar LI-17 lateral al cartílago tiroides'
  },
  {
    id: 'LI18',
    name: 'Futu',
    pinyin: 'Futu',
    meridian: 'LI',
    meridianName: 'Intestino Grueso',
    location: 'Nivel manzana de Adán, entre ECM',
    indications: ['Disfonía', 'inflamación laríngea'],
    contraindications: ['Evitar carótida'],
    applications: 'Acción local laríngea',
    benefits: 'Nervio laríngeo',
    techniques: '0.5–1 cun',
    observations: 'Ilustrar LI-18 en borde ECM'
  },
  {
    id: 'LI19',
    name: 'Kouheliao',
    pinyin: 'Kouheliao',
    meridian: 'LI',
    meridianName: 'Intestino Grueso',
    location: '0.5 cun lateral al surco nasolabial, bajo ala nasal',
    indications: ['Rinitis', 'congestión nasal'],
    contraindications: ['Sin riesgo mayor'],
    applications: 'Mejora drenaje nasal',
    benefits: 'Nervio infraorbitario',
    techniques: '0.3–0.5 cun',
    observations: 'Ilustrar LI-19 bajo ala nasal'
  },
  {
    id: 'LI20',
    name: 'Yingxiang',
    pinyin: 'Yingxiang',
    meridian: 'LI',
    meridianName: 'Intestino Grueso',
    location: 'En surco nasolabial, nivel ala nasal',
    indications: ['Sinusitis', 'anosmia'],
    contraindications: ['Evitar inserción profunda'],
    applications: 'Mejora ventilación nasal; vasodilatación local',
    benefits: 'Nervio infraorbitario',
    techniques: '0.3–0.5 cun',
    observations: 'Ilustrar LI-20 en surco nasolabial'
  },
  {
    id: 'ST1',
    name: 'Chengqi',
    pinyin: 'Chengqi',
    meridian: 'ST',
    meridianName: 'Estómago',
    location: 'Entre el globo ocular y el borde infraorbitario, con el ojo mirando al frente',
    indications: ['Blefaritis', 'neuralgia infraorbitaria'],
    contraindications: ['Riesgo ocular; no manipular profundamente'],
    applications: 'Regula circulación local; posible efecto sobre nervio infraorbitario',
    benefits: 'Nervio infraorbitario',
    techniques: '0.5–1 cun perpendicular suave',
    observations: 'Ilustrar ST-1 bajo la pupila, entre globo ocular y reborde infraorbitario'
  },
  {
    id: 'ST2',
    name: 'Sibai',
    pinyin: 'Sibai',
    meridian: 'ST',
    meridianName: 'Estómago',
    location: 'En el foramen infraorbitario',
    indications: ['Neuralgia facial', 'sinusitis'],
    contraindications: ['Evitar penetración profunda'],
    applications: 'Mejora circulación periorbitaria',
    benefits: 'Nervio infraorbitario',
    techniques: '0.3–0.5 cun',
    observations: 'Ilustrar ST-2 en foramen infraorbitario'
  },
  {
    id: 'ST3',
    name: 'Juliao',
    pinyin: 'Juliao',
    meridian: 'ST',
    meridianName: 'Estómago',
    location: 'Nivel ala nasal, línea vertical pupilar',
    indications: ['Sinusitis', 'neuralgia maxilar'],
    contraindications: ['Precaución vascular facial'],
    applications: 'Regula drenaje maxilar',
    benefits: 'Nervio infraorbitario',
    techniques: '0.3–0.5 cun',
    observations: 'Ilustrar ST-3 bajo pómulo en línea pupilar'
  },
  {
    id: 'ST4',
    name: 'Dicang',
    pinyin: 'Dicang',
    meridian: 'ST',
    meridianName: 'Estómago',
    location: '0.4 cun lateral comisura labial',
    indications: ['Parálisis facial'],
    contraindications: ['Sin riesgo mayor'],
    applications: 'Estimula nervio facial',
    benefits: 'Rama bucal nervio facial',
    techniques: '0.3–0.5 cun',
    observations: 'Ilustrar ST-4 lateral a comisura labial'
  },
  {
    id: 'ST5',
    name: 'Daying',
    pinyin: 'Daying',
    meridian: 'ST',
    meridianName: 'Estómago',
    location: 'Anterior al ángulo mandibular',
    indications: ['Bruxismo', 'neuralgia mandibular'],
    contraindications: ['Evitar arteria facial'],
    applications: 'Relaja masetero',
    benefits: 'Nervio facial',
    techniques: '0.5–1 cun',
    observations: 'Ilustrar ST-5 sobre masetero'
  },
  {
    id: 'ST6',
    name: 'Jiache',
    pinyin: 'Jiache',
    meridian: 'ST',
    meridianName: 'Estómago',
    location: 'Prominencia masetero al morder',
    indications: ['Dolor ATM'],
    contraindications: ['Sin riesgo mayor'],
    applications: 'Relaja musculatura masticatoria',
    benefits: 'Nervio facial',
    techniques: '0.5–1 cun',
    observations: 'Ilustrar ST-6 en masetero prominente'
  },
  {
    id: 'ST7',
    name: 'Xiaguan',
    pinyin: 'Xiaguan',
    meridian: 'ST',
    meridianName: 'Estómago',
    location: 'Depresión anterior al cóndilo mandibular',
    indications: ['Dolor ATM', 'tinnitus'],
    contraindications: ['Evitar penetración profunda'],
    applications: 'Modulación articulación temporomandibular',
    benefits: 'Nervio auriculotemporal',
    techniques: '0.5–1 cun',
    observations: 'Ilustrar ST-7 anterior al cóndilo mandibular'
  },
  {
    id: 'ST8',
    name: 'Touwei',
    pinyin: 'Touwei',
    meridian: 'ST',
    meridianName: 'Estómago',
    location: '0.5 cun dentro línea anterior del cabello',
    indications: ['Cefalea frontal'],
    contraindications: ['Sin riesgo mayor'],
    applications: 'Modulación vascular frontal',
    benefits: 'Nervio supraorbitario',
    techniques: '0.5 cun subcutáneo',
    observations: 'Ilustrar ST-8 en línea anterior cabello'
  },
  {
    id: 'ST9',
    name: 'Renying',
    pinyin: 'Renying',
    meridian: 'ST',
    meridianName: 'Estómago',
    location: 'Nivel cartílago tiroides, sobre arteria carótida',
    indications: ['Hipertensión leve'],
    contraindications: ['Evitar carótida'],
    applications: 'Influencia barorreceptores',
    benefits: 'Arteria carótida',
    techniques: '0.5–1 cun lateral',
    observations: 'Ilustrar ST-9 lateral cartílago tiroides'
  },
  {
    id: 'ST10',
    name: 'Shuitu',
    pinyin: 'Shuitu',
    meridian: 'ST',
    meridianName: 'Estómago',
    location: '1.5 cun inferior a ST-9',
    indications: ['Disfonía'],
    contraindications: ['Evitar carótida'],
    applications: 'Modulación cervical',
    benefits: 'Nervio laríngeo',
    techniques: '0.5–1 cun',
    observations: 'Ilustrar ST-10 bajo ST-9'
  },
  {
    id: 'ST11',
    name: 'Qishe',
    pinyin: 'Qishe',
    meridian: 'ST',
    meridianName: 'Estómago',
    location: 'Borde superior clavícula, esternal',
    indications: ['Dolor clavicular'],
    contraindications: ['Precaución pleura'],
    applications: 'Relaja musculatura',
    benefits: 'Plexo cervical',
    techniques: '0.3–0.5 cun',
    observations: 'Ilustrar ST-11 sobre clavícula medial'
  },
  {
    id: 'ST12',
    name: 'Quepen',
    pinyin: 'Quepen',
    meridian: 'ST',
    meridianName: 'Estómago',
    location: 'Fosa supraclavicular',
    indications: ['Asma', 'congestión torácica'],
    contraindications: ['Evitar punción profunda'],
    applications: 'Modula plexo braquial',
    benefits: 'Plexo braquial',
    techniques: '0.3–0.5 cun',
    observations: 'Ilustrar ST-12 en fosa supraclavicular'
  },
  {
    id: 'ST13',
    name: 'Qihu',
    pinyin: 'Qihu',
    meridian: 'ST',
    meridianName: 'Estómago',
    location: '4 cun lateral línea media, 1er espacio intercostal',
    indications: ['Dolor torácico'],
    contraindications: ['Riesgo neumotórax'],
    applications: 'Regula expansión torácica',
    benefits: 'Nervios intercostales',
    techniques: '0.5 cun oblicua',
    observations: 'Ilustrar ST-13 en primer espacio intercostal'
  },
  {
    id: 'ST14',
    name: 'Kufang',
    pinyin: 'Kufang',
    meridian: 'ST',
    meridianName: 'Estómago',
    location: '4 cun lateral línea media, 1er espacio intercostal inferior',
    indications: ['Dolor torácico'],
    contraindications: ['Riesgo pleural'],
    applications: 'Acción miofascial',
    benefits: 'Intercostales',
    techniques: '0.5 cun',
    observations: 'Ilustrar ST-14 en segundo espacio intercostal'
  },
  {
    id: 'ST15',
    name: 'Wuyi',
    pinyin: 'Wuyi',
    meridian: 'ST',
    meridianName: 'Estómago',
    location: '4 cun lateral línea media, 2° espacio intercostal',
    indications: ['Mastalgia'],
    contraindications: ['Precaución pleura'],
    applications: 'Mejora circulación local',
    benefits: 'Intercostales',
    techniques: '0.5 cun',
    observations: 'Ilustrar ST-15 segundo espacio intercostal'
  },
  {
    id: 'ST16',
    name: 'Yingchuang',
    pinyin: 'Yingchuang',
    meridian: 'ST',
    meridianName: 'Estómago',
    location: '4 cun lateral línea media, 3er espacio intercostal',
    indications: ['Congestión torácica'],
    contraindications: ['Riesgo pleural'],
    applications: 'Expande tórax',
    benefits: 'Intercostales',
    techniques: '0.5 cun',
    observations: 'Ilustrar ST-16 tercer espacio intercostal'
  },
  {
    id: 'ST17',
    name: 'Ruzhong',
    pinyin: 'Ruzhong',
    meridian: 'ST',
    meridianName: 'Estómago',
    location: 'Centro pezón',
    indications: ['Punto anatómico de referencia'],
    contraindications: ['Prohibido punción'],
    applications: 'No se punciona',
    benefits: 'Tejido mamario',
    techniques: 'No aplicar',
    observations: 'Ilustrar ST-17 centro pezón'
  },
  {
    id: 'ST18',
    name: 'Rugen',
    pinyin: 'Rugen',
    meridian: 'ST',
    meridianName: 'Estómago',
    location: '4 cun lateral línea media, 5° espacio intercostal',
    indications: ['Mastitis'],
    contraindications: ['Riesgo pleural'],
    applications: 'Mejora drenaje mamario',
    benefits: 'Intercostales',
    techniques: '0.5 cun',
    observations: 'Ilustrar ST-18 quinto espacio intercostal'
  },
  {
    id: 'ST19',
    name: 'Burong',
    pinyin: 'Burong',
    meridian: 'ST',
    meridianName: 'Estómago',
    location: '2 cun lateral línea media, 6 cun sobre ombligo',
    indications: ['Dispepsia'],
    contraindications: ['Precaución peritoneal'],
    applications: 'Regula motilidad gástrica',
    benefits: 'Plexo celíaco',
    techniques: '0.5–1 cun',
    observations: 'Ilustrar ST-19 abdomen superior'
  },
  {
    id: 'ST20',
    name: 'Chengman',
    pinyin: 'Chengman',
    meridian: 'ST',
    meridianName: 'Estómago',
    location: '2 cun lateral línea media, 5 cun sobre ombligo',
    indications: ['Gastritis'],
    contraindications: ['Precaución peritoneal'],
    applications: 'Modula secreción gástrica',
    benefits: 'Plexo gástrico',
    techniques: '0.5–1 cun',
    observations: 'Ilustrar ST-20 abdomen superior'
  },
  {
    id: 'ST21',
    name: 'Liangmen',
    pinyin: 'Liangmen',
    meridian: 'ST',
    meridianName: 'Estómago',
    location: '2 cun lateral línea media, 4 cun sobre ombligo',
    indications: ['Reflujo'],
    contraindications: ['Precaución profunda'],
    applications: 'Mejora vaciamiento gástrico',
    benefits: 'Inervación T7–T9',
    techniques: '0.5–1 cun',
    observations: 'Ilustrar ST-21 abdomen'
  },
  {
    id: 'ST22',
    name: 'Guanmen',
    pinyin: 'Guanmen',
    meridian: 'ST',
    meridianName: 'Estómago',
    location: '2 cun lateral línea media, 3 cun sobre ombligo',
    indications: ['Distensión'],
    contraindications: ['Precaución peritoneal'],
    applications: 'Regula tránsito',
    benefits: 'Dermatoma T8',
    techniques: '0.5–1 cun',
    observations: 'Ilustrar ST-22 abdomen'
  },
  {
    id: 'ST23',
    name: 'Taiyi',
    pinyin: 'Taiyi',
    meridian: 'ST',
    meridianName: 'Estómago',
    location: '2 cun lateral línea media, 2 cun sobre ombligo',
    indications: ['Ansiedad digestiva'],
    contraindications: ['Precaución profunda'],
    applications: 'Modula eje intestino-cerebro',
    benefits: 'Plexo entérico',
    techniques: '0.5–1 cun',
    observations: 'Ilustrar ST-23 abdomen'
  },
  {
    id: 'ST24',
    name: 'Huaroumen',
    pinyin: 'Huaroumen',
    meridian: 'ST',
    meridianName: 'Estómago',
    location: '2 cun lateral línea media, 1 cun sobre ombligo',
    indications: ['Dolor epigástrico'],
    contraindications: ['Precaución peritoneal'],
    applications: 'Regula peristalsis',
    benefits: 'Dermatoma T9',
    techniques: '0.5–1 cun',
    observations: 'Ilustrar ST-24 abdomen'
  },
  {
    id: 'ST25',
    name: 'Tianshu',
    pinyin: 'Tianshu',
    meridian: 'ST',
    meridianName: 'Estómago',
    location: '2 cun lateral al ombligo',
    indications: ['Síndrome intestino irritable'],
    contraindications: ['Precaución peritoneal'],
    applications: 'Modula motilidad intestinal',
    benefits: 'Plexo mesentérico',
    techniques: '0.5–1.5 cun',
    observations: 'Ilustrar ST-25 lateral al ombligo'
  },
  {
    id: 'ST26',
    name: 'Wailing',
    pinyin: 'Wailing',
    meridian: 'ST',
    meridianName: 'Estómago',
    location: '2 cun lateral línea media, 1 cun bajo ombligo',
    indications: ['Dolor abdominal'],
    contraindications: ['Precaución profunda'],
    applications: 'Acción local visceral',
    benefits: 'Dermatoma T10',
    techniques: '0.5–1 cun',
    observations: 'Ilustrar ST-26 abdomen inferior'
  },
  {
    id: 'ST27',
    name: 'Daju',
    pinyin: 'Daju',
    meridian: 'ST',
    meridianName: 'Estómago',
    location: '2 cun lateral línea media, 2 cun bajo ombligo',
    indications: ['Disuria'],
    contraindications: ['Precaución peritoneal'],
    applications: 'Modula vejiga',
    benefits: 'Plexo hipogástrico',
    techniques: '0.5–1 cun',
    observations: 'Ilustrar ST-27 abdomen inferior'
  },
  {
    id: 'ST28',
    name: 'Shuidao',
    pinyin: 'Shuidao',
    meridian: 'ST',
    meridianName: 'Estómago',
    location: '2 cun lateral línea media, 3 cun bajo ombligo',
    indications: ['Retención líquidos'],
    contraindications: ['Precaución profunda'],
    applications: 'Influye sistema linfático',
    benefits: 'Plexo hipogástrico',
    techniques: '0.5–1 cun',
    observations: 'Ilustrar ST-28 abdomen inferior'
  },
  {
    id: 'ST29',
    name: 'Guilai',
    pinyin: 'Guilai',
    meridian: 'ST',
    meridianName: 'Estómago',
    location: '2 cun lateral línea media, 4 cun bajo ombligo',
    indications: ['Amenorrea'],
    contraindications: ['Precaución profunda'],
    applications: 'Influye flujo pélvico',
    benefits: 'Inervación pélvica',
    techniques: '0.5–1 cun',
    observations: 'Ilustrar ST-29 abdomen inferior'
  },
  {
    id: 'ST30',
    name: 'Qichong',
    pinyin: 'Qichong',
    meridian: 'ST',
    meridianName: 'Estómago',
    location: '2 cun lateral sínfisis púbica',
    indications: ['Hernia inguinal'],
    contraindications: ['Evitar arteria femoral'],
    applications: 'Influye plexo femoral',
    benefits: 'Arteria femoral',
    techniques: '0.5–1 cun',
    observations: 'Ilustrar ST-30 región inguinal'
  },
  {
    id: 'ST31',
    name: 'Biguan',
    pinyin: 'Biguan',
    meridian: 'ST',
    meridianName: 'Estómago',
    location: 'Unión muslo y cadera anterior',
    indications: ['Dolor cadera'],
    contraindications: ['Sin riesgo mayor'],
    applications: 'Relaja flexores cadera',
    benefits: 'Nervio femoral',
    techniques: '1–1.5 cun',
    observations: 'Ilustrar ST-31 pliegue inguinal lateral'
  },
  {
    id: 'ST32',
    name: 'Futu',
    pinyin: 'Futu',
    meridian: 'ST',
    meridianName: 'Estómago',
    location: '6 cun sobre borde superior patela',
    indications: ['Dolor muslo'],
    contraindications: ['Sin riesgo mayor'],
    applications: 'Acción miofascial',
    benefits: 'Nervio femoral',
    techniques: '1–1.5 cun',
    observations: 'Ilustrar ST-32 muslo anterior'
  },
  {
    id: 'ST33',
    name: 'Yinshi',
    pinyin: 'Yinshi',
    meridian: 'ST',
    meridianName: 'Estómago',
    location: '3 cun sobre borde superior patela',
    indications: ['Dolor rodilla'],
    contraindications: ['Sin riesgo mayor'],
    applications: 'Modula articulación rodilla',
    benefits: 'Dermatoma L3',
    techniques: '1–1.5 cun',
    observations: 'Ilustrar ST-33 muslo anterior inferior'
  },
  {
    id: 'ST34',
    name: 'Liangqiu',
    pinyin: 'Liangqiu',
    meridian: 'ST',
    meridianName: 'Estómago',
    location: '2 cun sobre borde superolateral patela',
    indications: ['Dolor agudo rodilla'],
    contraindications: ['Sin riesgo mayor'],
    applications: 'Punto Xi; analgesia local',
    benefits: 'Nervio femoral',
    techniques: '0.8–1.5 cun',
    observations: 'Ilustrar ST-34 encima patela lateral'
  },
  {
    id: 'ST35',
    name: 'Dubi',
    pinyin: 'Dubi',
    meridian: 'ST',
    meridianName: 'Estómago',
    location: 'Depresión lateral ligamento patelar',
    indications: ['Dolor rodilla'],
    contraindications: ['Sin riesgo mayor'],
    applications: 'Acción intraarticular refleja',
    benefits: 'Nervio peroneo',
    techniques: '0.5–1 cun',
    observations: 'Ilustrar ST-35 lateral patela'
  },
  {
    id: 'ST36',
    name: 'Zusanli',
    pinyin: 'Zusanli',
    meridian: 'ST',
    meridianName: 'Estómago',
    location: '3 cun bajo ST-35, 1 dedo lateral cresta tibial',
    indications: ['Dispepsia', 'fatiga', 'dolor rodilla'],
    contraindications: ['Sin riesgo mayor'],
    applications: 'Modulación inmunitaria; eje intestino-inmunidad',
    benefits: 'Nervio peroneo profundo',
    techniques: '1–2 cun',
    observations: 'Ilustrar ST-36 3 cun bajo rodilla'
  },
  {
    id: 'ST37',
    name: 'Shangjuxu',
    pinyin: 'Shangjuxu',
    meridian: 'ST',
    meridianName: 'Estómago',
    location: '3 cun bajo ST-36',
    indications: ['Colitis'],
    contraindications: ['Sin riesgo mayor'],
    applications: 'Acción intestino delgado refleja',
    benefits: 'Dermatoma L5',
    techniques: '1–1.5 cun',
    observations: 'Ilustrar ST-37 bajo ST-36'
  },
  {
    id: 'ST38',
    name: 'Tiaokou',
    pinyin: 'Tiaokou',
    meridian: 'ST',
    meridianName: 'Estómago',
    location: '8 cun bajo ST-35',
    indications: ['Hombro doloroso'],
    contraindications: ['Sin riesgo mayor'],
    applications: 'Conexión refleja hombro-pierna',
    benefits: 'Nervio peroneo',
    techniques: '1–1.5 cun',
    observations: 'Ilustrar ST-38 pierna anterior'
  },
  {
    id: 'ST39',
    name: 'Xiajuxu',
    pinyin: 'Xiajuxu',
    meridian: 'ST',
    meridianName: 'Estómago',
    location: '3 cun bajo ST-37',
    indications: ['Trastornos intestinales'],
    contraindications: ['Sin riesgo mayor'],
    applications: 'Regula colon',
    benefits: 'Dermatoma L5',
    techniques: '1–1.5 cun',
    observations: 'Ilustrar ST-39 bajo ST-37'
  },
  {
    id: 'ST40',
    name: 'Fenglong',
    pinyin: 'Fenglong',
    meridian: 'ST',
    meridianName: 'Estómago',
    location: '8 cun sobre maléolo lateral, lateral tibia',
    indications: ['Hiperlipidemia leve', 'flema'],
    contraindications: ['Sin riesgo mayor'],
    applications: 'Influencia metabólica',
    benefits: 'Nervio peroneo',
    techniques: '1–1.5 cun',
    observations: 'Ilustrar ST-40 lateral tibia'
  },
  {
    id: 'ST41',
    name: 'Jiexi',
    pinyin: 'Jiexi',
    meridian: 'ST',
    meridianName: 'Estómago',
    location: 'Centro pliegue anterior tobillo',
    indications: ['Dolor tobillo'],
    contraindications: ['Sin riesgo mayor'],
    applications: 'Regula movilidad articular',
    benefits: 'Nervio peroneo profundo',
    techniques: '0.5–1 cun',
    observations: 'Ilustrar ST-41 pliegue tobillo'
  },
  {
    id: 'ST42',
    name: 'Chongyang',
    pinyin: 'Chongyang',
    meridian: 'ST',
    meridianName: 'Estómago',
    location: 'Dorso pie, entre 2° y 3° metatarsiano',
    indications: ['Dolor pie'],
    contraindications: ['Evitar arteria dorsal'],
    applications: 'Modulación vascular dorsal',
    benefits: 'Arteria dorsal del pie',
    techniques: '0.3–0.5 cun',
    observations: 'Ilustrar ST-42 dorso pie'
  },
  {
    id: 'ST43',
    name: 'Xiangu',
    pinyin: 'Xiangu',
    meridian: 'ST',
    meridianName: 'Estómago',
    location: 'Depresión distal unión 2° y 3° metatarsiano',
    indications: ['Edema pie'],
    contraindications: ['Sin riesgo mayor'],
    applications: 'Acción local',
    benefits: 'Nervio digital dorsal',
    techniques: '0.5 cun',
    observations: 'Ilustrar ST-43 dorso pie'
  },
  {
    id: 'ST44',
    name: 'Neiting',
    pinyin: 'Neiting',
    meridian: 'ST',
    meridianName: 'Estómago',
    location: 'Entre 2° y 3° dedo pie',
    indications: ['Dolor dental', 'inflamación'],
    contraindications: ['Sin riesgo mayor'],
    applications: 'Punto Ying; efecto antiinflamatorio',
    benefits: 'Nervios digitales',
    techniques: '0.3–0.5 cun',
    observations: 'Ilustrar ST-44 entre dedos pie'
  },
  {
    id: 'ST45',
    name: 'Lidui',
    pinyin: 'Lidui',
    meridian: 'ST',
    meridianName: 'Estómago',
    location: '0.1 cun ángulo ungueal lateral 2° dedo',
    indications: ['Fiebre', 'síncope leve'],
    contraindications: ['Punción superficial'],
    applications: 'Punto Jing-Well; estimulación distal SNC',
    benefits: 'Terminaciones digitales',
    techniques: '0.1 cun',
    observations: 'Ilustrar ST-45 ángulo ungueal lateral segundo dedo'
  }
];
