
import { AcupuncturePoint } from './types';

export const MERIDIANS = [
  { code: 'LU', name: 'Pulmón', color: 'bg-slate-400' },
  { code: 'LI', name: 'Intestino Grueso', color: 'bg-yellow-600' },
  { code: 'ST', name: 'Estómago', color: 'bg-yellow-400' },
  { code: 'SP', name: 'Bazo', color: 'bg-yellow-500' },
  { code: 'HT', name: 'Corazón', color: 'bg-red-500' },
  { code: 'SI', name: 'Intestino Delgado', color: 'bg-red-600' },
  { code: 'BL', name: 'Vejiga', color: 'bg-blue-600' },
  { code: 'KI', name: 'Riñón', color: 'bg-blue-800' },
  { code: 'PC', name: 'Pericardio', color: 'bg-red-400' },
  { code: 'SJ', name: 'San Jiao', color: 'bg-orange-500' },
  { code: 'GB', name: 'Vesícula Biliar', color: 'bg-green-600' },
  { code: 'LR', name: 'Hígado', color: 'bg-green-800' },
  { code: 'GV', name: 'Du Mai (Gobernador)', color: 'bg-purple-600' },
  { code: 'CV', name: 'Ren Mai (Concepción)', color: 'bg-indigo-600' },
];

// Imagen única proporcionada para el meridiano de Pulmón
const IMG_LUNG_MAP = "https://i.ibb.co/XfqM9Gkz/lung-channel-map.jpg"; 

export const INITIAL_POINTS: AcupuncturePoint[] = [
  {
    id: 'LU1',
    name: 'Zhongfu',
    pinyin: 'Zhōngfǔ',
    meridian: 'LU',
    meridianName: 'Pulmón',
    location: 'En la parte lateral del pecho, en el 1er espacio intercostal, 6 cun lateral a la línea media anterior.',
    indications: ['Tos', 'Asma', 'Opresión torácica', 'Dolor de hombro y espalda'],
    contraindications: ['Punción profunda prohibida (riesgo de neumotórax).'],
    applications: 'Tratamiento de exceso de moco, bronquitis aguda y asma.',
    benefits: 'Punto Mu Frontal del Pulmón. Regula el Qi de pulmón, transforma la flema y despeja el calor.',
    techniques: 'Inserción oblicua 0.5-0.8 cun hacia la parte lateral del tórax.',
    observations: 'Punto de intersección con el meridiano de Bazo.',
    staticImage: IMG_LUNG_MAP
  },
  {
    id: 'LU2',
    name: 'Yunmen',
    pinyin: 'Yúnmén',
    meridian: 'LU',
    meridianName: 'Pulmón',
    location: 'En la fosa infraclavicular, en la depresión medial al proceso coracoides.',
    indications: ['Tos', 'Asma', 'Dolor en el pecho y hombro'],
    contraindications: ['No punción profunda (neumotórax).'],
    applications: 'Alivio de la opresión en el tórax superior y agitación.',
    benefits: 'Despeja el pulmón y detiene la tos. Abre el tórax.',
    techniques: 'Inserción oblicua 0.5-0.8 cun.',
    observations: 'Significa "Puerta de las Nubes".',
    staticImage: IMG_LUNG_MAP
  },
  {
    id: 'LU3',
    name: 'Tianfu',
    pinyin: 'Tiānfǔ',
    meridian: 'LU',
    meridianName: 'Pulmón',
    location: 'En la cara radial del brazo, 3 cun por debajo del extremo del pliegue axilar.',
    indications: ['Hemorragia nasal', 'Asma', 'Tos', 'Dolor en el brazo'],
    contraindications: ['Ninguna.'],
    applications: 'Trastornos emocionales relacionados con el pulmón (tristeza).',
    benefits: 'Punto "Ventana del Cielo". Calma el espíritu y regula el Qi.',
    techniques: 'Inserción perpendicular 0.5-1.0 cun.',
    observations: 'Punto importante para la conexión pulmón-mente.',
    staticImage: IMG_LUNG_MAP
  },
  {
    id: 'LU4',
    name: 'Xiabai',
    pinyin: 'Xiábái',
    meridian: 'LU',
    meridianName: 'Pulmón',
    location: 'En la cara radial del brazo, 4 cun por debajo del extremo del pliegue axilar.',
    indications: ['Tos', 'Dolor en el pecho', 'Palpitaciones', 'Dolor de brazo'],
    contraindications: ['Ninguna.'],
    applications: 'Tos con dolor irradiado al brazo.',
    benefits: 'Regula el Qi y la sangre, calma el dolor.',
    techniques: 'Inserción perpendicular 0.5-1.0 cun.',
    observations: 'Significa "Blanco Protector".',
    staticImage: IMG_LUNG_MAP
  },
  {
    id: 'LU5',
    name: 'Chize',
    pinyin: 'Chǐzé',
    meridian: 'LU',
    meridianName: 'Pulmón',
    location: 'En el pliegue del codo, en el borde radial del tendón del bíceps braquial.',
    indications: ['Fiebre', 'Tos con flema', 'Asma', 'Dolor de garganta', 'Vómitos'],
    contraindications: ['Evitar arteria braquial.'],
    applications: 'Bronquitis, amigdalitis, dolores de codo y brazo.',
    benefits: 'Punto He-Mar (Agua). Despeja el calor de pulmón y desciende el Qi rebelde.',
    techniques: 'Inserción perpendicular 0.5-1.0 cun.',
    observations: 'Punto de sedación del meridiano.',
    staticImage: IMG_LUNG_MAP
  },
  {
    id: 'LU6',
    name: 'Kongzui',
    pinyin: 'Kǒngzuì',
    meridian: 'LU',
    meridianName: 'Pulmón',
    location: 'Cara radial del antebrazo, 7 cun por encima del pliegue de la muñeca.',
    indications: ['Hemoptisis', 'Dolor de garganta', 'Asma aguda', 'Cough'],
    contraindications: ['Ninguna.'],
    applications: 'Crisis asmáticas, hemorragias pulmonares súbitas.',
    benefits: 'Punto Xi-Hendidura. Detiene hemorragias y alivia casos agudos.',
    techniques: 'Inserción perpendicular 0.5-1.2 cun.',
    observations: 'Excelente para el tratamiento de síntomas pulmonares severos repentinos.',
    staticImage: IMG_LUNG_MAP
  },
  {
    id: 'LU7',
    name: 'Lieque',
    pinyin: 'Lièquē',
    meridian: 'LU',
    meridianName: 'Pulmón',
    location: '1.5 cun sobre el pliegue de la muñeca, en la depresión del proceso estiloides del radio.',
    indications: ['Cefalea', 'Rigidez de nuca', 'Tos', 'Parálisis facial'],
    contraindications: ['Ninguna.'],
    applications: 'Gripe, resfriado, migrañas temporales.',
    benefits: 'Punto Luo. Maestro del Ren Mai. Comando de la nuca y cabeza.',
    techniques: 'Inserción oblicua 0.3-0.5 cun hacia el codo.',
    observations: 'Punto fundamental para expulsar el viento externo.',
    staticImage: IMG_LUNG_MAP
  },
  {
    id: 'LU8',
    name: 'Jingqu',
    pinyin: 'Jīngqú',
    meridian: 'LU',
    meridianName: 'Pulmón',
    location: '1 cun sobre el pliegue de la muñeca, en la depresión medial al estiloides radial.',
    indications: ['Asma', 'Tos', 'Dolor de garganta', 'Fiebre'],
    contraindications: ['No se recomienda moxibustión directa.'],
    applications: 'Tratamiento de la tos crónica y asma.',
    benefits: 'Punto Jing-Río (Metal). Punto de tonificación.',
    techniques: 'Inserción perpendicular 0.3-0.5 cun.',
    observations: 'Significa "Canal del Paso".',
    staticImage: IMG_LUNG_MAP
  },
  {
    id: 'LU9',
    name: 'Taiyuan',
    pinyin: 'Tàiyuán',
    meridian: 'LU',
    meridianName: 'Pulmón',
    location: 'En el pliegue de la muñeca, en la fosa lateral a la arteria radial.',
    indications: ['Asma', 'Tos', 'Debilidad de pulso', 'Dolor de pecho'],
    contraindications: ['Evitar arteria radial.'],
    applications: 'Tonificación general del Qi y Yin de pulmón.',
    benefits: 'Punto Shu-Arroyo. Punto Yuan. Punto Influente de los Vasos.',
    techniques: 'Inserción perpendicular 0.3-0.5 cun.',
    observations: 'Punto muy importante para nutrir el órgano pulmón.',
    staticImage: IMG_LUNG_MAP
  },
  {
    id: 'LU10',
    name: 'Yuji',
    pinyin: 'Yújì',
    meridian: 'LU',
    meridianName: 'Pulmón',
    location: 'En el punto medio del primer hueso metacarpiano, borde piel roja y blanca.',
    indications: ['Fiebre', 'Dolor de garganta', 'Hemoptisis', 'Tos'],
    contraindications: ['Ninguna.'],
    applications: 'Amigdalitis aguda y calor en las palmas.',
    benefits: 'Punto Ying-Manantial (Fuego). Despeja calor de pulmón y beneficia la garganta.',
    techniques: 'Inserción perpendicular 0.5-0.8 cun.',
    observations: 'Punto clave para el "Calor de Pulmón".',
    staticImage: IMG_LUNG_MAP
  },
  {
    id: 'LU11',
    name: 'Shaoshang',
    pinyin: 'Shàoshāng',
    meridian: 'LU',
    meridianName: 'Pulmón',
    location: 'En el lado radial del pulgar, 0.1 cun proximal a la esquina de la uña.',
    indications: ['Pérdida de conciencia', 'Dolor de garganta agudo', 'Manía', 'Fiebre alta'],
    contraindications: ['Ninguna.'],
    applications: 'Casos de emergencia y reanimación.',
    benefits: 'Punto Jing-Pozo (Madera). Despeja el calor y abre los orificios.',
    techniques: 'Inserción superficial 0.1 cun o sangría.',
    observations: 'Se suele pinchar para sangrar en amigdalitis severas.',
    staticImage: IMG_LUNG_MAP
  }
];
